### ISSUE TITLE
redundancy again and again.

### ISSUE THREAD

**Issue by rcrath** [digiah/dahiweb#11]
Problematic behavior:
home page shows same potentially info in slide show, recent, events, and research, depending on tags.  Looks like we have little content since we repeat it right from the home page.

Desired behavior: write some flow control logic for tags so if an item is tagged "featured" and thus placed in the slide show, it is automagically dropped from the home page feeds under "recent," events, and "research."

**Comment by damg70** [comment]
having more content would be a slightly easier solution, but will look into customizing php for our installation. if we did implement this logic now would it look like even less content on the site because there would be fewer items in the "recent" and "research" headings?

right now the posts are pulled into those three sections based on WP shortcodes via the "recent posts widget extended" widget, which is poorly documented.

**Comment by rcrath** [comment]
Would not be less content as it would just pull in stuff further down the list. We used to do this with RSS feeds rather than short-circuit. Might that be easier?
